/**
 * Usage page — generated by `intelligo add usage-page`.
 *
 * This file is YOURS. Intelligo will not overwrite it: once you edit
 * it, `intelligo upgrade --check` reports the upstream change as a
 * diff and leaves your version alone (ADR-0002).
 *
 * It reads through @intelligo-dev/executions' query API rather than the
 * database directly, so it keeps working across schema changes.
 */

import { requireWorkspace } from "@intelligo-dev/auth";
import { formatMoney, type Money } from "@intelligo-dev/core/money";
import { listExecutions, summarizeExecutions } from "@intelligo-dev/executions";

/** Amounts arrive as micros with their currency; never assume a symbol. */
const show = (amounts: Money[]) =>
  amounts.length === 0
    ? "—"
    : amounts.map((amount) => formatMoney(amount, "en-US")).join(" · ");

export default async function UsagePage() {
  const { workspace } = await requireWorkspace();

  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

  const [summary, recent] = await Promise.all([
    summarizeExecutions(workspace.id, { from: monthStart, to: now }),
    listExecutions({ workspaceId: workspace.id, limit: 20 }),
  ]);

  return (
    <main style={{ fontFamily: "system-ui", padding: "2rem" }}>
      <h1>Usage</h1>

      <p>
        {summary.totals.count} executions this month ·{" "}
        {summary.totals.totalTokens.toLocaleString()} tokens ·{" "}
        {show(summary.totals.charged)}
      </p>

      <table cellPadding={8}>
        <thead>
          <tr>
            <th align="left">Capability</th>
            <th align="left">Status</th>
            <th align="right">Tokens</th>
            <th align="right">Charged</th>
            <th align="left">Started</th>
          </tr>
        </thead>
        <tbody>
          {recent.map((e) => (
            <tr key={e.id}>
              <td>{e.capability}</td>
              <td>{e.status}</td>
              <td align="right">{e.totalTokens ?? 0}</td>
              <td align="right">
                {e.chargedMicros !== null && e.currency
                  ? formatMoney(
                      { amount: e.chargedMicros, currency: e.currency } as Money,
                      "en-US"
                    )
                  : "—"}
              </td>
              <td>{e.startedAt.toISOString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </main>
  );
}
