/**
 * `intelligo add <feature>` — generate consumer-owned source.
 *
 * "Owned" is the operative word (ADR-0002): the files land in the
 * consumer's repository and Intelligo stops deciding what is in them.
 * The manifest records what was written and its hash so a later
 * upgrade can tell an untouched file from one the consumer has made
 * their own, and refuse to overwrite the latter.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import {
  emptyManifest,
  hashContents,
  readManifest,
  recordFeature,
  writeManifest,
  type GeneratedFile,
} from "../manifest.js";

export type TemplateFile = { template: string; target: string };
export type TemplateFeature = {
  templateVersion: string;
  description: string;
  /** Set when a registry item supersedes this template feature. */
  deprecated?: string;
  files: TemplateFile[];
};
export type TemplateCatalogue = Record<string, TemplateFeature>;

export function readCatalogue(templatesDir: string): TemplateCatalogue {
  return JSON.parse(
    readFileSync(path.join(templatesDir, "manifest.json"), "utf8")
  ) as TemplateCatalogue;
}

export type AddResult = {
  feature: string;
  /** The catalogue's deprecation notice, when the feature has one. */
  deprecated?: string;
  written: string[];
  /** Present and modified by the consumer — left untouched. */
  skippedCustomized: string[];
  /** Present but not ours (no manifest record) — left untouched. */
  skippedUnknown: string[];
};

export type AddOptions = {
  appRoot: string;
  templatesDir: string;
  frameworkVersion: string;
  /** Re-write files the consumer has customized. Off by default. */
  force?: boolean;
  /**
   * Placeholder substitutions applied to template contents, e.g.
   * `{ __APP_NAME__: "acme" }`. Applied before hashing, so the
   * recorded hash describes what actually landed on disk.
   */
  variables?: Record<string, string>;
};

export function substitute(
  contents: string,
  variables: Record<string, string> | undefined
): string {
  if (!variables) return contents;
  return Object.entries(variables).reduce(
    (out, [key, value]) => out.split(key).join(value),
    contents
  );
}

export function addFeature(feature: string, options: AddOptions): AddResult {
  const catalogue = readCatalogue(options.templatesDir);
  const spec = catalogue[feature];
  if (!spec) {
    throw new Error(
      `Unknown feature "${feature}". Available: ${Object.keys(catalogue).join(", ")}`
    );
  }

  const manifest =
    readManifest(options.appRoot) ?? emptyManifest(options.frameworkVersion);
  const previous = manifest.features[feature];
  const previousByPath = new Map(
    (previous?.files ?? []).map((f) => [f.path, f])
  );

  const result: AddResult = {
    feature,
    written: [],
    skippedCustomized: [],
    skippedUnknown: [],
  };
  if (spec.deprecated) result.deprecated = spec.deprecated;
  const recorded: GeneratedFile[] = [];

  for (const file of spec.files) {
    const source = path.join(options.templatesDir, file.template);
    const target = path.join(options.appRoot, file.target);
    const contents = substitute(
      readFileSync(source, "utf8"),
      options.variables
    );

    if (existsSync(target) && !options.force) {
      const current = hashContents(readFileSync(target, "utf8"));
      const known = previousByPath.get(file.target);

      if (!known) {
        // Not ours: a file we never generated already occupies the
        // path. Overwriting it would destroy work we cannot attribute.
        result.skippedUnknown.push(file.target);
        continue;
      }
      if (current !== known.hash) {
        result.skippedCustomized.push(file.target);
        // Keep the ORIGINAL hash: it is the baseline that says "this is
        // customized", and replacing it with the current hash would
        // silently re-adopt the consumer's file as ours.
        recorded.push(known);
        continue;
      }
    }

    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, contents);
    recorded.push({ path: file.target, hash: hashContents(contents) });
    result.written.push(file.target);
  }

  writeManifest(
    options.appRoot,
    recordFeature(
      manifest,
      feature,
      spec.templateVersion,
      recorded,
      options.variables
    )
  );

  return result;
}

export function formatAddResult(r: AddResult): string {
  const lines = [`${r.feature}:`];
  if (r.deprecated) lines.push(`  ⚠ deprecated: ${r.deprecated}`);
  for (const f of r.written) lines.push(`  + ${f}`);
  for (const f of r.skippedCustomized)
    lines.push(`  = ${f} (yours — left alone; use --force to overwrite)`);
  for (const f of r.skippedUnknown)
    lines.push(`  ! ${f} (already exists and was not generated by Intelligo)`);
  if (r.written.length === 0 && r.skippedCustomized.length === 0)
    lines.push("  nothing to do");
  return lines.join("\n");
}
