/**
 * Every docs page as Markdown, at its URL with `.md` appended — what an
 * agent reads instead of the rendered page (llms.txt points here). The
 * body is the committed source, snippets already inlined.
 */
import type { APIRoute, GetStaticPaths } from "astro";

import { orderedDocs, type DocEntry } from "@/lib/docs-nav";
import { SITE } from "@/lib/site";

export const getStaticPaths = (async () => {
  const docs = await orderedDocs();
  return docs.map((entry) => ({
    params: { slug: entry.id },
    props: { entry },
  }));
}) satisfies GetStaticPaths;

export const GET: APIRoute<{ entry: DocEntry }> = ({ props, site }) => {
  const { entry } = props;
  const body = (entry.body ?? "")
    .replace(/^\s*<!-- Generated by [^\n]*-->\n*/, "")
    .trim();
  const source = new URL(`/docs/${entry.id}`, site).href;
  const markdown = `# ${entry.data.title}\n\n> ${entry.data.description}\n\nSource: ${source} · ${SITE.brand} docs\n\n${body}\n`;
  return new Response(markdown, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
};
