/**
 * Billing page — generated by `intelligo add billing-page`.
 *
 * Yours from here. It reads the plan catalogue your composition root
 * registered rather than a list baked into the framework, so changing
 * your prices is a change to your own `lib/plans.ts` (ADR-0006).
 */

import { requireWorkspace } from "@intelligo-dev/auth";
import { getWorkspaceBilling } from "@intelligo-dev/billing";
import { getPlanConfigs } from "@intelligo-dev/billing/plans";
import { CreditBalance } from "@intelligo-dev/ui";

import { PRODUCT_SLUG } from "@/lib/intelligo";

/**
 * Your currency, in one place. @intelligo-dev/ui takes a formatter rather
 * than assuming one, because a framework package deciding that money
 * is written "5,000₮" is wrong everywhere but here.
 */
const formatAmount = (amount: number) => `${amount.toLocaleString()}₮`;

export const dynamic = "force-dynamic";

export default async function BillingPage() {
  const { workspace } = await requireWorkspace();

  const [billing, plans] = await Promise.all([
    getWorkspaceBilling(workspace.id),
    Promise.resolve(getPlanConfigs(PRODUCT_SLUG)),
  ]);

  const currentSlug = billing.plan?.slug ?? "free";

  return (
    <main style={{ fontFamily: "system-ui", padding: "2rem" }}>
      <h1>Billing</h1>

      <p>
        Current plan: <strong>{billing.plan?.name ?? "Free"}</strong>
      </p>

      <CreditBalance
        remainingMnt={billing.creditBalance.balanceMnt ?? 0}
        formatAmount={formatAmount}
      />

      <section>
        <h2>Plans</h2>
        {Object.values(plans).map((plan) => (
          <article key={plan.slug} style={{ marginBottom: "1.5rem" }}>
            <h3>
              {plan.name}
              {plan.slug === currentSlug ? " (current)" : ""}
            </h3>
            <p>{plan.description}</p>
            <p>
              {plan.priceOneTime === 0
                ? "Free"
                : formatAmount(plan.priceOneTime)}
            </p>
            <ul>
              {plan.features.map((f) => (
                <li key={f}>{f}</li>
              ))}
            </ul>
          </article>
        ))}
      </section>
    </main>
  );
}
