/**
 * The docs at intelligo.dev/docs cannot drift from the framework.
 *
 * Reference pages (packages, CLI, install order, config seams) are
 * generated by apps/website/scripts/docs.mjs from the files that are the
 * truth; hand-written pages pull their code through snippets.
 * This suite regenerates both and fails when what is committed differs —
 * the fix is `pnpm sync`, never an edit to a generated page.
 *
 * What generation cannot cover — prose naming an API, a link to a page —
 * is checked here too: a name a hand-written page puts in code must exist
 * in the framework, an import it shows must be a real export, and every
 * internal link must land on a page the site builds.
 */

import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

import {
  APPS_DIR,
  PACKAGES_DIR,
  ROOT,
  listPublishedWorkspaces,
  walk,
} from "./tree";

type DocsModule = {
  DOCS_DIR: string;
  DOC_SECTIONS: readonly { id: string; title: string }[];
  isGenerated: (rel: string) => boolean;
  generateDocs: (root: string) => Record<string, string>;
  generateData: (root: string) => Record<string, string>;
  generateLlmsTxt: (siteRoot: string) => Record<string, string>;
  applySnippets: (markdown: string, root: string) => string;
  docFiles: (siteRoot: string) => string[];
};

const SITE = path.join(APPS_DIR, "website");
const docs = (await import(path.join(SITE, "scripts/docs.mjs"))) as DocsModule;
const DOCS = path.join(SITE, docs.DOCS_DIR);
const MARKER = "<!-- Generated by apps/website/scripts/docs.mjs";

const files = docs.docFiles(SITE);
const handWritten = files.filter((f) => !docs.isGenerated(f));
const read = (rel: string) => readFileSync(path.join(DOCS, rel), "utf8");
const STALE = "stale — run `pnpm sync` from the repository root";

describe("generated docs", () => {
  const generated = docs.generateDocs(ROOT);

  it("every generated page is committed and current", () => {
    const stale = Object.entries(generated)
      .filter(
        ([rel, content]) =>
          !existsSync(path.join(DOCS, rel)) || read(rel) !== content
      )
      .map(([rel]) => rel);
    expect(stale, STALE).toEqual([]);
  });

  it("no page in a generated path outlives its source", () => {
    const orphans = files.filter(
      (f) => docs.isGenerated(f) && !(f in generated)
    );
    expect(orphans, STALE).toEqual([]);
  });

  it("only generated pages carry the generated marker", () => {
    expect(handWritten.filter((f) => read(f).includes(MARKER))).toEqual([]);
  });

  it("the site's data files are current", () => {
    const stale = Object.entries(docs.generateData(ROOT))
      .filter(
        ([rel, content]) =>
          readFileSync(path.join(SITE, rel), "utf8") !== content
      )
      .map(([rel]) => rel);
    expect(stale, STALE).toEqual([]);
  });

  it("llms.txt and llms-full.txt are current", () => {
    const stale = Object.entries(docs.generateLlmsTxt(SITE))
      .filter(
        ([rel, content]) =>
          readFileSync(path.join(SITE, rel), "utf8") !== content
      )
      .map(([rel]) => rel);
    expect(stale, STALE).toEqual([]);
  });

  it("DOC_SECTIONS matches src/lib/docs-nav.ts's copy", () => {
    // docs.mjs runs under plain Node and can't import an astro:content
    // module, so its DOC_SECTIONS is a deliberate duplicate — this is the
    // guard against the two drifting apart.
    const navSource = readFileSync(
      path.join(SITE, "src/lib/docs-nav.ts"),
      "utf8"
    );
    const missing = docs.DOC_SECTIONS.filter(
      ({ id, title }) =>
        !navSource.includes(`id: "${id}"`) ||
        !navSource.includes(`title: "${title}"`)
    );
    expect(missing).toEqual([]);
  });

  it("no page points readers at the ADRs, which are the maintainers' record", () => {
    const pages = [
      ...Object.entries(generated),
      ...handWritten.map((f) => [f, read(f)] as const),
    ];
    const leaks = pages
      .filter(([, md]) => /ADR-\d{4}|docs\/adr|\/docs\/decisions/.test(md))
      .map(([rel]) => rel);
    expect(leaks).toEqual([]);
  });

  it("snippets in hand-written pages match their source", () => {
    const stale = handWritten.filter(
      (f) => docs.applySnippets(read(f), ROOT) !== read(f)
    );
    expect(stale, STALE).toEqual([]);
  });
});

describe("hand-written docs", () => {
  /** Pages the site builds outside the docs collection. */
  const registry = JSON.parse(
    readFileSync(path.join(PACKAGES_DIR, "registry/registry.json"), "utf8")
  ) as { items: { name: string; type: string }[] };
  const routes = new Set([
    "/",
    "/blocks",
    "/components",
    "/architecture",
    "/why",
    "/docs",
    ...registry.items
      .filter((i) => i.type === "registry:block" && i.name !== "smoke")
      .map((i) => `/blocks/${i.name}`),
    ...files.map(
      (f) => `/docs/${f.replace(/\.md$/, "").replace(/\/?index$/, "")}`
    ),
  ]);

  it("every internal link lands on a page the site builds", () => {
    const broken = files.flatMap((f) =>
      [...read(f).matchAll(/\]\((\/[^)\s#?]*)/g)]
        .map((m) => m[1]!.replace(/\/$/, "") || "/")
        .filter((href) => !routes.has(href) && !href.startsWith("/r/"))
        .map((href) => `${f}: ${href}`)
    );
    expect(broken).toEqual([]);
  });

  /** Every name any framework source declares or mentions: packages, registry, scaffold, reference app. */
  const corpus = new Set<string>();
  for (const dir of [PACKAGES_DIR, path.join(APPS_DIR, "app")]) {
    for (const file of walk(
      dir,
      (n) => /\.(ts|tsx|tpl|json)$/.test(n) && !n.endsWith(".test.ts")
    )) {
      for (const m of readFileSync(file, "utf8").matchAll(/[A-Za-z_$][\w$]*/g))
        corpus.add(m[0]);
    }
  }

  /** Names a page says do NOT exist, on purpose. */
  const ABSENT_BY_DESIGN = new Set([
    "IntelligoAgent",
    "IntelligoTool",
    "IntelligoWorkflow",
    "IntelligoMemory",
  ]);

  it("every API a page names in inline code exists in the framework", () => {
    const identifier =
      /^(?:[a-z][A-Za-z0-9]*\.)?([a-z]+[A-Z][A-Za-z0-9]*|[A-Z][a-z0-9]+[A-Z][A-Za-z0-9]*)(?:\(\))?$/;
    const missing = handWritten.flatMap((f) =>
      [
        ...read(f)
          .replace(/```[\s\S]*?```/g, "")
          .matchAll(/`([^`\n]+)`/g),
      ]
        .map((m) => m[1]!.match(identifier)?.[1])
        .filter(
          (name): name is string =>
            !!name && !corpus.has(name) && !ABSENT_BY_DESIGN.has(name)
        )
        .map((name) => `${f}: ${name}`)
    );
    expect(missing).toEqual([]);
  });

  /** Names exported anywhere in a published package's source. */
  const exportsOf = new Map<string, Set<string>>();
  for (const pkg of listPublishedWorkspaces(PACKAGES_DIR)) {
    const names = new Set<string>();
    for (const file of walk(
      path.join(PACKAGES_DIR, pkg, "src"),
      (n) => /\.tsx?$/.test(n) && !/\.test\.tsx?$/.test(n)
    )) {
      const text = readFileSync(file, "utf8");
      for (const m of text.matchAll(
        /export\s+(?:declare\s+)?(?:default\s+)?(?:async\s+)?(?:function\*?|const|let|class|interface|type|enum)\s+([\w$]+)/g
      ))
        names.add(m[1]!);
      for (const m of text.matchAll(/export\s+(?:type\s+)?\{([^}]*)\}/g)) {
        for (const part of m[1]!.split(",")) {
          const name = part
            .trim()
            .replace(/^type\s+/, "")
            .split(/\s+as\s+/)
            .pop();
          if (name) names.add(name);
        }
      }
    }
    exportsOf.set(pkg, names);
  }

  it("every import a page shows from @intelligo-dev/* is a real export", () => {
    const missing = handWritten.flatMap((f) =>
      [
        ...read(f).matchAll(
          /import\s*(?:type\s*)?\{([^}]*)\}\s*from\s*"@intelligo-dev\/([\w-]+)[^"]*"/g
        ),
      ].flatMap((m) =>
        m[1]!
          .split(",")
          .map(
            (p) =>
              p
                .trim()
                .replace(/^type\s+/, "")
                .split(/\s+as\s+/)[0]!
          )
          .filter((name) => name && !exportsOf.get(m[2]!)?.has(name))
          .map((name) => `${f}: ${name} from @intelligo-dev/${m[2]}`)
      )
    );
    expect(missing).toEqual([]);
  });
});

/**
 * /architecture and /why show test titles and installed paths as
 * evidence. A title is evidence only while a test carries it, and a path
 * only while the block writes it.
 */
describe("quoted evidence", async () => {
  const { RULES } = (await import(path.join(SITE, "src/lib/rules.ts"))) as {
    RULES: { id: string; file: string; passing: string; output: string[] }[];
  };
  const { BLOCKERS } = (await import(
    path.join(SITE, "src/lib/blockers.ts")
  )) as { BLOCKERS: { tag: string; evidence: string[] }[] };

  const isTest = (name: string) => /\.test\.tsx?$/.test(name);
  /** A test or suite title, as the source spells it. */
  const titled = (source: string, title: string) =>
    source.includes(`("${title}"`);
  const checked = (line: string) => line.replace(/^✓\s*/, "");

  it("every rule quotes a title its test file carries", () => {
    const missing = RULES.flatMap((rule) => {
      const abs = path.join(ROOT, rule.file);
      if (!existsSync(abs)) return [`${rule.id}: ${rule.file} does not exist`];
      const source = readFileSync(abs, "utf8");
      const title = checked(rule.passing);
      const failing = rule.output.find((l) => l.startsWith("× ")) ?? "";
      return [
        ...(titled(source, title) ? [] : [`${rule.id}: "${title}"`]),
        ...(failing.endsWith(` › ${title}`)
          ? []
          : [`${rule.id}: the failing line names another test`]),
      ];
    });
    expect(missing).toEqual([]);
  });

  it("every test a card ticks exists under the path it runs", () => {
    const missing = BLOCKERS.flatMap((card) => {
      const run = /^\$ pnpm vitest run (\S+)$/.exec(card.evidence[0] ?? "");
      if (!run) return [];
      const sources = walk(path.join(ROOT, run[1]!), isTest).map((f) =>
        readFileSync(f, "utf8")
      );
      return card.evidence
        .slice(1)
        .map(checked)
        .filter((title) => !sources.some((s) => titled(s, title)))
        .map((title) => `${card.tag}: "${title}" under ${run[1]}`);
    });
    expect(missing).toEqual([]);
  });

  it("the quickstart's terminal is what the CLI would print", async () => {
    const { QUICKSTART } = (await import(
      path.join(SITE, "src/lib/quickstart.ts")
    )) as { QUICKSTART: { title: string; out: string[] }[] };
    const out = (title: string) =>
      QUICKSTART.find((step) => step.title === title)!.out;
    const cli = path.join(PACKAGES_DIR, "cli");

    const scaffold = (
      JSON.parse(
        readFileSync(path.join(cli, "templates/manifest.json"), "utf8")
      ) as Record<string, { files: unknown[] }>
    )["app-scaffold"]!.files.length;
    expect(out("Create")).toContain(`◆ Scaffolded ${scaffold} files in my-app`);

    const flow = readFileSync(
      path.join(cli, "src/commands/create-flow.ts"),
      "utf8"
    );
    const suggested = [
      .../const SUGGESTED = \[([^\]]*)\]/
        .exec(flow)![1]!
        .matchAll(/"([^"]+)"/g),
    ].map((m) => m[1]!);
    const pages = out("Create")
      .filter((line) => line.includes("shadcn add"))
      .at(-1)!;
    for (const name of suggested)
      expect(pages).toContain(`@intelligo/${name} `);

    const chain = walk(
      path.join(PACKAGES_DIR, "core/src/db/migrations"),
      (name) => name.endsWith(".sql")
    )
      .map((file) => path.basename(file, ".sql"))
      .sort();
    expect(out("Migrate")).toEqual([
      `✓ Applied ${chain.length} migration(s):`,
      ...chain.map((tag) => `    ${tag}`),
    ]);
  });

  it("the README's quickstart is the site's, in one install spelling", async () => {
    const { QUICKSTART } = (await import(
      path.join(SITE, "src/lib/quickstart.ts")
    )) as { QUICKSTART: { cmd: string }[] };
    const readme = readFileSync(path.join(ROOT, "README.md"), "utf8");

    const block = readme.slice(
      readme.indexOf("\n## Quickstart\n"),
      readme.indexOf("\n## One request")
    );
    const commands = [
      ...block.matchAll(/^(pnpm \S+(?: [^#\n]*?)?)\s*(?:#.*)?$/gm),
    ]
      .map((m) => m[1]!.trim())
      .filter((cmd) => cmd !== "cd my-app");
    expect(commands).toEqual(QUICKSTART.map((step) => step.cmd));

    const installs = [
      ...readme.matchAll(/(?:[\w-]+ [\w-]+ )?shadcn add [^\s`"]+/g),
    ];
    expect(installs.length).toBeGreaterThan(0);
    for (const [spelling] of installs)
      expect(spelling).toMatch(/^pnpm exec shadcn add @intelligo\//);
  });

  it("the film's acts and captions are the composition's", async () => {
    const { FILM_CHAPTERS, FILM_SECONDS } = (await import(
      path.join(SITE, "src/lib/film.ts")
    )) as {
      FILM_CHAPTERS: { at: number; title: string; line: string }[];
      FILM_SECONDS: number;
    };
    const film = readFileSync(
      path.join(ROOT, "tools/film/src/Film.tsx"),
      "utf8"
    );
    const captions = readFileSync(
      path.join(SITE, "public/film/film.en.vtt"),
      "utf8"
    );

    const scenes = /^const SCENE = \{\n([\s\S]*?)^\};/m.exec(film)![1]!;
    const starts = [...scenes.matchAll(/: \[([\d.]+),/g)].map(
      (m) => Number(m[1]) * FILM_SECONDS
    );
    expect(FILM_CHAPTERS.map((chapter) => chapter.at)).toEqual(
      starts.map((s) => Number(s.toFixed(1)))
    );

    for (const chapter of FILM_CHAPTERS) {
      expect(film).toContain(`title: "${chapter.title}"`);
      for (const sentence of chapter.line.split(/(?<=\.)\s+/)) {
        expect(film).toContain(sentence);
        expect(captions).toContain(sentence);
      }
    }
  });

  it("every path a card installs is a target of the blocks it adds", () => {
    const registry = JSON.parse(
      readFileSync(path.join(PACKAGES_DIR, "registry/registry.json"), "utf8")
    ) as { items: { name: string; files: { target?: string }[] }[] };

    const missing = BLOCKERS.flatMap((card) => {
      const add = /^\$ pnpm exec shadcn add (.+)$/.exec(card.evidence[0] ?? "");
      if (!add) return [];
      const names = add[1]!
        .split(/\s+/)
        .map((n) => n.replace("@intelligo/", ""));
      const targets = new Set(
        registry.items
          .filter((item) => names.includes(item.name))
          .flatMap((item) => item.files.map((file) => file.target))
      );
      return card.evidence
        .slice(1)
        .map(checked)
        .filter((target) => !targets.has(target))
        .map((target) => `${card.tag}: ${target}`);
    });
    expect(missing).toEqual([]);
  });
});
