/**
 * The docs at intelligo.dev/docs cannot drift from the framework.
 *
 * Reference pages (packages, CLI, install order, config seams) are
 * generated by apps/website/scripts/docs.mjs from the files that are the
 * truth; hand-written pages pull their code through snippets.
 * This suite regenerates both and fails when what is committed differs —
 * the fix is `pnpm sync`, never an edit to a generated page.
 *
 * What generation cannot cover — prose naming an API, a link to a page —
 * is checked here too: a name a hand-written page puts in code must exist
 * in the framework, an import it shows must be a real export, and every
 * internal link must land on a page the site builds.
 */

import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

import {
  APPS_DIR,
  PACKAGES_DIR,
  ROOT,
  listPublishedWorkspaces,
  walk,
} from "./tree";

type DocsModule = {
  DOCS_DIR: string;
  DOC_SECTIONS: readonly { id: string; title: string }[];
  isGenerated: (rel: string) => boolean;
  generateDocs: (root: string) => Record<string, string>;
  generateData: (root: string) => Record<string, string>;
  generateLlmsTxt: (siteRoot: string) => Record<string, string>;
  applySnippets: (markdown: string, root: string) => string;
  docFiles: (siteRoot: string) => string[];
};

const SITE = path.join(APPS_DIR, "website");
const docs = (await import(path.join(SITE, "scripts/docs.mjs"))) as DocsModule;
const DOCS = path.join(SITE, docs.DOCS_DIR);
const MARKER = "<!-- Generated by apps/website/scripts/docs.mjs";

const files = docs.docFiles(SITE);
const handWritten = files.filter((f) => !docs.isGenerated(f));
const read = (rel: string) => readFileSync(path.join(DOCS, rel), "utf8");
const STALE = "stale — run `pnpm sync` from the repository root";

describe("generated docs", () => {
  const generated = docs.generateDocs(ROOT);

  it("every generated page is committed and current", () => {
    const stale = Object.entries(generated)
      .filter(
        ([rel, content]) =>
          !existsSync(path.join(DOCS, rel)) || read(rel) !== content
      )
      .map(([rel]) => rel);
    expect(stale, STALE).toEqual([]);
  });

  it("no page in a generated path outlives its source", () => {
    const orphans = files.filter(
      (f) => docs.isGenerated(f) && !(f in generated)
    );
    expect(orphans, STALE).toEqual([]);
  });

  it("only generated pages carry the generated marker", () => {
    expect(handWritten.filter((f) => read(f).includes(MARKER))).toEqual([]);
  });

  it("the site's data files are current", () => {
    const stale = Object.entries(docs.generateData(ROOT))
      .filter(
        ([rel, content]) =>
          readFileSync(path.join(SITE, rel), "utf8") !== content
      )
      .map(([rel]) => rel);
    expect(stale, STALE).toEqual([]);
  });

  it("llms.txt and llms-full.txt are current", () => {
    const stale = Object.entries(docs.generateLlmsTxt(SITE))
      .filter(
        ([rel, content]) =>
          readFileSync(path.join(SITE, rel), "utf8") !== content
      )
      .map(([rel]) => rel);
    expect(stale, STALE).toEqual([]);
  });

  it("DOC_SECTIONS matches src/lib/docs-nav.ts's copy", () => {
    // docs.mjs runs under plain Node and can't import an astro:content
    // module, so its DOC_SECTIONS is a deliberate duplicate — this is the
    // guard against the two drifting apart.
    const navSource = readFileSync(
      path.join(SITE, "src/lib/docs-nav.ts"),
      "utf8"
    );
    const missing = docs.DOC_SECTIONS.filter(
      ({ id, title }) =>
        !navSource.includes(`id: "${id}"`) ||
        !navSource.includes(`title: "${title}"`)
    );
    expect(missing).toEqual([]);
  });

  it("no page points readers at the ADRs, which are the maintainers' record", () => {
    const pages = [
      ...Object.entries(generated),
      ...handWritten.map((f) => [f, read(f)] as const),
    ];
    const leaks = pages
      .filter(([, md]) => /ADR-\d{4}|docs\/adr|\/docs\/decisions/.test(md))
      .map(([rel]) => rel);
    expect(leaks).toEqual([]);
  });

  it("snippets in hand-written pages match their source", () => {
    const stale = handWritten.filter(
      (f) => docs.applySnippets(read(f), ROOT) !== read(f)
    );
    expect(stale, STALE).toEqual([]);
  });
});

describe("hand-written docs", () => {
  /** Pages the site builds outside the docs collection. */
  const registry = JSON.parse(
    readFileSync(path.join(PACKAGES_DIR, "registry/registry.json"), "utf8")
  ) as { items: { name: string; type: string }[] };
  const routes = new Set([
    "/",
    "/blocks",
    "/components",
    "/architecture",
    "/why",
    "/docs",
    ...registry.items
      .filter((i) => i.type === "registry:block" && i.name !== "smoke")
      .map((i) => `/blocks/${i.name}`),
    ...files.map(
      (f) => `/docs/${f.replace(/\.md$/, "").replace(/\/?index$/, "")}`
    ),
  ]);

  it("every internal link lands on a page the site builds", () => {
    const broken = files.flatMap((f) =>
      [...read(f).matchAll(/\]\((\/[^)\s#?]*)/g)]
        .map((m) => m[1]!.replace(/\/$/, "") || "/")
        .filter((href) => !routes.has(href) && !href.startsWith("/r/"))
        .map((href) => `${f}: ${href}`)
    );
    expect(broken).toEqual([]);
  });

  /** Every name any framework source declares or mentions: packages, registry, scaffold, reference app. */
  const corpus = new Set<string>();
  for (const dir of [PACKAGES_DIR, path.join(APPS_DIR, "app")]) {
    for (const file of walk(
      dir,
      (n) => /\.(ts|tsx|tpl|json)$/.test(n) && !n.endsWith(".test.ts")
    )) {
      for (const m of readFileSync(file, "utf8").matchAll(/[A-Za-z_$][\w$]*/g))
        corpus.add(m[0]);
    }
  }

  /** Names a page says do NOT exist, on purpose. */
  const ABSENT_BY_DESIGN = new Set([
    "IntelligoAgent",
    "IntelligoTool",
    "IntelligoWorkflow",
    "IntelligoMemory",
  ]);

  it("every API a page names in inline code exists in the framework", () => {
    const identifier =
      /^(?:[a-z][A-Za-z0-9]*\.)?([a-z]+[A-Z][A-Za-z0-9]*|[A-Z][a-z0-9]+[A-Z][A-Za-z0-9]*)(?:\(\))?$/;
    const missing = handWritten.flatMap((f) =>
      [
        ...read(f)
          .replace(/```[\s\S]*?```/g, "")
          .matchAll(/`([^`\n]+)`/g),
      ]
        .map((m) => m[1]!.match(identifier)?.[1])
        .filter(
          (name): name is string =>
            !!name && !corpus.has(name) && !ABSENT_BY_DESIGN.has(name)
        )
        .map((name) => `${f}: ${name}`)
    );
    expect(missing).toEqual([]);
  });

  /** Names exported anywhere in a published package's source. */
  const exportsOf = new Map<string, Set<string>>();
  for (const pkg of listPublishedWorkspaces(PACKAGES_DIR)) {
    const names = new Set<string>();
    for (const file of walk(
      path.join(PACKAGES_DIR, pkg, "src"),
      (n) => /\.tsx?$/.test(n) && !/\.test\.tsx?$/.test(n)
    )) {
      const text = readFileSync(file, "utf8");
      for (const m of text.matchAll(
        /export\s+(?:declare\s+)?(?:default\s+)?(?:async\s+)?(?:function\*?|const|let|class|interface|type|enum)\s+([\w$]+)/g
      ))
        names.add(m[1]!);
      for (const m of text.matchAll(/export\s+(?:type\s+)?\{([^}]*)\}/g)) {
        for (const part of m[1]!.split(",")) {
          const name = part
            .trim()
            .replace(/^type\s+/, "")
            .split(/\s+as\s+/)
            .pop();
          if (name) names.add(name);
        }
      }
    }
    exportsOf.set(pkg, names);
  }

  it("every import a page shows from @intelligo-dev/* is a real export", () => {
    const missing = handWritten.flatMap((f) =>
      [
        ...read(f).matchAll(
          /import\s*(?:type\s*)?\{([^}]*)\}\s*from\s*"@intelligo-dev\/([\w-]+)[^"]*"/g
        ),
      ].flatMap((m) =>
        m[1]!
          .split(",")
          .map(
            (p) =>
              p
                .trim()
                .replace(/^type\s+/, "")
                .split(/\s+as\s+/)[0]!
          )
          .filter((name) => name && !exportsOf.get(m[2]!)?.has(name))
          .map((name) => `${f}: ${name} from @intelligo-dev/${m[2]}`)
      )
    );
    expect(missing).toEqual([]);
  });
});
