#!/usr/bin/env node
/**
 * Generates tsconfig.paths.json so the registry type-checks in place,
 * against what it ships.
 *
 * Every target an item ships resolves to the item's own source under
 * base/, so a cross-item import (`@/lib/chat-config` from a chat
 * component) is checked against the registry's copy — not against
 * apps/app's installed copy of it, which is allowed to drift into the
 * consumer-owned seam. Only what no item ships — the shadcn primitives
 * under components/ui and the files `intelligo create` scaffolds
 * (requires.json `scaffold`) — falls through to the reference app,
 * which holds the same files a consumer would.
 *
 * This is tests/architecture/registry.test.ts's "@/ imports resolve to
 * a shipped target" rule expressed as module resolution. Regenerated by
 * `pnpm type-check`; gitignored, so it cannot go stale.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REGISTRY = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export function derivePaths(registry) {
  const paths = {};
  for (const item of registry.items) {
    for (const file of item.files) {
      if (!file.target || !/\.tsx?$/.test(file.target)) continue;
      const key = "@/" + file.target.replace(/\.tsx?$/, "");
      paths[key] = ["./" + file.path.replace(/\.tsx?$/, "")];
    }
  }
  // TypeScript picks the longest matching pattern, so every exact key
  // above wins over this catch-all.
  const sorted = Object.fromEntries(Object.entries(paths).sort());
  sorted["@/*"] = ["../../apps/app/*"];
  return sorted;
}

const registry = JSON.parse(
  readFileSync(resolve(REGISTRY, "registry.json"), "utf8")
);
writeFileSync(
  resolve(REGISTRY, "tsconfig.paths.json"),
  JSON.stringify(
    { compilerOptions: { paths: derivePaths(registry) } },
    null,
    2
  ) + "\n"
);
