{
  "name": "__APP_NAME__",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "next dev --turbopack --port 3000",
    "build": "next build",
    "start": "next start --port 3000",
    "type-check": "tsc --noEmit",
    "db:generate": "drizzle-kit generate",
    "db:migrate": "intelligo migrate && drizzle-kit migrate",
    "db:check": "intelligo migrate --check"
  },
  "dependencies": {
    "@base-ui/react": "^1.8.0",
    "@intelligo-dev/admin": "__INTELLIGO_DEP__",
    "@intelligo-dev/audit": "__INTELLIGO_DEP__",
    "@intelligo-dev/auth": "__INTELLIGO_DEP__",
    "@intelligo-dev/billing": "__INTELLIGO_DEP__",
    "@intelligo-dev/chat": "__INTELLIGO_DEP__",
    "@intelligo-dev/core": "__INTELLIGO_DEP__",
    "@intelligo-dev/executions": "__INTELLIGO_DEP__",
    "@intelligo-dev/jobs": "__INTELLIGO_DEP__",
    "@intelligo-dev/next": "__INTELLIGO_DEP__",
    "class-variance-authority": "^0.7.1",
    "cn": "^0.3.0",
    "drizzle-orm": "^0.45.1",
    "lucide-react": "^1.45.0",
    "next": "^16.2.3",
    "next-intl": "^4.9.2",
    "next-themes": "^0.4.6",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "server-only": "^0.0.1",
    "sonner": "^2.0.7"
  },
  "devDependencies": {
    "@intelligo-dev/cli": "__INTELLIGO_DEP__",
    "@tailwindcss/postcss": "^4",
    "@types/node": "^22.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "dotenv": "^16.4.7",
    "drizzle-kit": "^0.31.8",
    "shadcn": "^4.21.0",
    "tailwindcss": "^4",
    "tw-animate-css": "^1.4.0",
    "typescript": "^5.7.2"
  }
}
