{
  "name": "__APP_NAME__",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "next dev --turbopack --port 3000",
    "build": "next build",
    "start": "next start --port 3000",
    "type-check": "tsc --noEmit",
    "db:generate": "drizzle-kit generate",
    "db:migrate": "intelligo migrate && drizzle-kit migrate",
    "db:check": "intelligo migrate --check"
  },
  "dependencies": {
    "@base-ui/react": "^1.8.0",
    "@intelligo-dev/admin": "__INTELLIGO_DEP__",
    "@intelligo-dev/audit": "__INTELLIGO_DEP__",
    "@intelligo-dev/auth": "__INTELLIGO_DEP__",
    "@intelligo-dev/billing": "__INTELLIGO_DEP__",
    "@intelligo-dev/chat": "__INTELLIGO_DEP__",
    "@intelligo-dev/core": "__INTELLIGO_DEP__",
    "@intelligo-dev/executions": "__INTELLIGO_DEP__",
    "@intelligo-dev/jobs": "__INTELLIGO_DEP__",
    "@intelligo-dev/next": "__INTELLIGO_DEP__",
    "ai": "^7.0.103",
    "better-auth": "~1.6.33",
    "class-variance-authority": "^0.7.1",
    "cn": "^0.3.0",
    "drizzle-orm": "^0.45.2",
    "lucide-react": "^1.46.0",
    "next": "~16.3.5",
    "next-intl": "^4.14.5",
    "next-themes": "^0.4.6",
    "react": "^19.3.0",
    "react-dom": "^19.3.0",
    "server-only": "^0.0.1",
    "sonner": "^2.0.8",
    "stripe": "^22.6.2",
    "zod": "^4.6.5"
  },
  "devDependencies": {
    "@intelligo-dev/cli": "__INTELLIGO_DEP__",
    "@tailwindcss/postcss": "^4.3.3",
    "@types/node": "^22.20.3",
    "@types/react": "^19.3.0",
    "@types/react-dom": "^19.3.0",
    "dotenv": "^17.4.2",
    "drizzle-kit": "^0.31.10",
    "pg": "8.18.0",
    "shadcn": "^4.21.0",
    "tailwindcss": "^4.3.3",
    "tw-animate-css": "^1.4.0",
    "typescript": "^5.9.3"
  }
}
