/**
 * The docs that must not be written by hand.
 *
 * Reference material — a page per package, the CLI, the registry's
 * install order and its config seams — is generated from the files that
 * are the truth (package READMEs and manifests, the CLI's own doc
 * comments and template manifest, packages/registry), so it
 * cannot describe an API, a command or a file that no longer exists.
 * Hand-written pages keep their code honest through snippets: a fenced
 * block right after `<!-- snippet: path#symbol -->` is replaced with that
 * declaration from the real file.
 *
 * The ADRs are the maintainers' record, not reader documentation: a
 * reference to one is stripped from everything generated here, and the
 * docs test refuses one in a hand-written page.
 *
 * Pure functions over the repository root. `sync-framework.mjs` writes
 * what they return; tests/architecture/docs.test.ts fails when what is
 * committed differs, so a stale page is a red build, not a quiet lie.
 */
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { createRequire } from "node:module";
import { basename, dirname, join, relative, resolve } from "node:path";

const GITHUB = "https://github.com/intelligo-dev/intelligo";
const SITE_URL = "https://intelligo.dev";

/** Where the docs live, relative to the site. */
export const DOCS_DIR = "src/content/docs";

/**
 * The docs sections, in reading order — the same list as
 * src/lib/docs-nav.ts's DOC_SECTIONS (an id is a doc's first path
 * segment); tests/architecture/docs.test.ts checks the two stay equal.
 * Duplicated rather than imported because this file runs under plain
 * Node (no Astro/TypeScript step) and docs-nav.ts depends on
 * `astro:content`, which only exists inside Astro's build.
 */
export const DOC_SECTIONS = [
  { id: "getting-started", title: "Getting started" },
  { id: "concepts", title: "Concepts" },
  { id: "registry", title: "Registry" },
  { id: "packages", title: "Packages" },
  { id: "cli", title: "CLI" },
  { id: "guides", title: "Guides" },
];

/** Paths under DOCS_DIR that only the generator writes. */
export const GENERATED = [
  "packages/",
  "cli/",
  "registry/install-order.md",
  "registry/config-seams.md",
  "getting-started/environment.md",
];

export const isGenerated = (rel) =>
  GENERATED.some((g) => (g.endsWith("/") ? rel.startsWith(g) : rel === g));

/** A registry file a deployment edits, by the way such files are named. */
export const SEAM =
  /^lib\/[^/]*(config|steps|renderers|patterns|bootstrap)\.tsx?$/;

/** A `lib/` file is also a seam when its own doc comment says it is the consumer's. */
const SAYS_CONSUMER_OWNED = /consumer-owned/i;

const marker = (source) =>
  `<!-- Generated by apps/website/scripts/docs.mjs from ${source}. Edit that, then run \`pnpm sync\`. -->`;

const read = (root, p) => readFileSync(join(root, p), "utf8");

/** Every file under a directory. */
function walkFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walkFiles(join(dir, e.name)) : [join(dir, e.name)]
  );
}

function frontmatter(fields) {
  const lines = Object.entries(fields)
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => `${k}: ${typeof v === "number" ? v : JSON.stringify(v)}`);
  return `---\n${lines.join("\n")}\n---\n\n`;
}

/** `/** … *\/` → Markdown paragraphs. */
function commentToMarkdown(block) {
  const lines = block
    .replace(/^\/\*\*\s*\n?/, "")
    .replace(/\s*\*\/$/, "")
    .split("\n")
    .map((l) => l.replace(/^\s*\* ?/, ""));
  return fenceIndentedCode(lines).join("\n").trim();
}

/**
 * Source comments indent their examples by two or three spaces, which
 * Markdown reads as a paragraph. A run of indented lines that starts
 * after a blank line and is not a list becomes a fenced block.
 */
function fenceIndentedCode(lines) {
  const out = [];
  let i = 0;
  const indented = (l) => /^ {2,}\S/.test(l);
  while (i < lines.length) {
    const startsRun =
      indented(lines[i]) &&
      !/^\s*([-*+]|\d+[.)])\s/.test(lines[i]) &&
      (i === 0 || lines[i - 1].trim() === "");
    if (!startsRun) {
      out.push(lines[i++]);
      continue;
    }
    let j = i;
    while (j < lines.length && (indented(lines[j]) || lines[j].trim() === ""))
      j++;
    while (j > i && lines[j - 1].trim() === "") j--;
    const run = lines.slice(i, j);
    const pad = Math.min(
      ...run.filter((l) => l.trim()).map((l) => l.match(/^ */)[0].length)
    );
    out.push("```ts", ...run.map((l) => l.slice(pad)), "```");
    i = j;
  }
  return out;
}

/** The first `/** … *\/` in a source file, skipping directives and imports. */
function leadingDocComment(text) {
  const m = text.match(/\/\*\*[\s\S]*?\*\//);
  return m ? commentToMarkdown(m[0]) : "";
}

/** Relative links in a repository Markdown file → site or GitHub links. */
function rewriteLinks(md, sourcePath) {
  return md.replace(/\]\((?!https?:|#|\/|mailto:)([^)\s]+)\)/g, (_, target) => {
    const [file, hash] = target.split("#");
    const repoPath = join(dirname(sourcePath), file).split("\\").join("/");
    const pkg = repoPath.match(/^packages\/([^/]+)\/README\.md$/);
    if (pkg) return `](/docs/packages/${pkg[1]})`;
    return `](${GITHUB}/blob/main/${repoPath}${hash ? `#${hash}` : ""})`;
  });
}

/**
 * ADR references, which point readers at the maintainers' record: a
 * parenthetical "(ADR-nnnn)" or "(ADR-nnnn, T3; …)" goes, a linked
 * "[ADR-nnnn](…)" keeps nothing, "Per ADR-nnnn, x" reads "X", and "the
 * promise in ADR-nnnn" reads "the promise". The docs test fails on any
 * form this does not cover, so a new one is a rule here or a rewording
 * at the source. The character classes below stay [^()\n] rather than
 * [^()] on purpose — a negated class matches newlines too, so an
 * unbounded one can span from an unrelated earlier "(" to a later ")"
 * whenever an ADR id sits somewhere between them, corrupting unrelated
 * paragraphs. Every real citation lives on one line.
 */
export function stripAdrRefs(md) {
  return md
    .replace(
      /[ \t]*\((?:[^()\n]*?[;,]\s*)?(?:see |per |from )?\[?ADR-\d{4}\]?(?:\([^)\n]*\))?(?:[^()\n]|\([^()\n]*\))*\)/g,
      ""
    )
    .replace(/\bPer\s+ADR-\d{4}(?:\s*\([^)\n]*\))?,\s*(\w)/g, (_, c) =>
      c.toUpperCase()
    )
    .replace(/\bADR-\d{4}\s+is\s+explicit\s+that\s+(\w)/g, (_, c) =>
      c.toUpperCase()
    )
    .replace(/[ \t]+in\s+ADR-\d{4}\b/g, "")
    .replace(/\[(ADR-\d{4})\]\([^)\n]*\)/g, "$1");
}

function publishedPackages(root) {
  return readdirSync(join(root, "packages"))
    .filter((p) => existsSync(join(root, "packages", p, "package.json")))
    .map((p) => ({
      dir: p,
      manifest: JSON.parse(read(root, `packages/${p}/package.json`)),
    }))
    .filter((p) => p.manifest.private !== true);
}

/** Reading order for the package pages; a package not listed goes last. */
const PACKAGE_ORDER = [
  "core",
  "auth",
  "billing",
  "executions",
  "chat",
  "next",
  "audit",
  "jobs",
  "admin",
  "mastra",
  "cli",
];

// --- packages -------------------------------------------------------------

function packagePages(root) {
  const pkgs = publishedPackages(root).sort((a, b) => {
    const r = (p) => PACKAGE_ORDER.indexOf(p.dir) + 1 || 999;
    return r(a) - r(b) || a.dir.localeCompare(b.dir);
  });
  const out = {};
  pkgs.forEach(({ dir, manifest }, i) => {
    const source = `packages/${dir}/README.md`;
    let body = read(root, source)
      .replace(/^# .*\n/, "")
      .replace(/^[\s\S]*?(?=^## )/m, "") // the lead paragraph and the "Part of Intelligo" note
      .replace(/\n## Licen[cs]e[\s\S]*$/, "")
      .trim();
    body = rewriteLinks(body, source);
    const entries = Object.keys(manifest.exports ?? {}).map((k) =>
      k === "." ? manifest.name : `${manifest.name}${k.slice(1)}`
    );
    out[`packages/${dir}.md`] =
      frontmatter({
        title: manifest.name,
        description: manifest.description,
        order: i + 1,
        label: dir,
      }) +
      `${marker(`${source} and package.json`)}\n\n${body}\n\n` +
      (entries.length
        ? `## Entry points\n\n${entries.map((e) => `- \`${e}\``).join("\n")}\n\n`
        : "") +
      `[npm](https://www.npmjs.com/package/${manifest.name}) · [source](${GITHUB}/tree/main/packages/${dir})\n`;
  });

  out["packages/index.md"] =
    frontmatter({
      title: "Packages",
      description: `The ${pkgs.length} packages published under @intelligo-dev, at one version.`,
      order: 0,
      label: "Overview",
    }) +
    `${marker("each package's package.json")}\n\n` +
    `Every package is published at the same version, by one release commit. \`intelligo create\` adds the set an application needs. How the set is cut, and which package may import which: [package topology](/docs/concepts/package-topology).\n\n` +
    `| Package | What it is |\n| --- | --- |\n` +
    pkgs
      .map(
        ({ dir, manifest }) =>
          `| [${dir}](/docs/packages/${dir}) | ${manifest.description.replace(/\|/g, "\\|")} |`
      )
      .join("\n") +
    "\n";
  return out;
}

// --- CLI ------------------------------------------------------------------

const COMMANDS = [
  ["create", "packages/cli/src/commands/create.ts"],
  ["add", "packages/cli/src/commands/add.ts"],
  ["doctor", "packages/cli/src/commands/doctor.ts"],
  ["migrate", "packages/cli/src/commands/migrate.ts"],
  ["migrate --check", "packages/cli/src/commands/migrate-check.ts"],
  ["upgrade --check", "packages/cli/src/commands/upgrade-check.ts"],
];

function cliPage(root) {
  const bin = read(root, "packages/cli/src/bin.ts");
  const usageBlock = bin.match(
    /function usage\(\): string \{\s*return \[([\s\S]*?)\]\.join/
  );
  if (!usageBlock)
    throw new Error("docs: could not find usage() in packages/cli/src/bin.ts");
  const usage = [...usageBlock[1].matchAll(/"((?:[^"\\]|\\.)*)"/g)]
    .map((m) => m[1].replace(/\\"/g, '"'))
    .filter((l) => l !== "")
    // A command line gains the binary's name; the line continuing it
    // keeps its column under the description.
    .map((l) =>
      l.replace(/^ {2}(?=(\S)?)/, (_, word) =>
        word ? "intelligo " : " ".repeat("intelligo ".length)
      )
    )
    .join("\n");

  const catalogue = JSON.parse(
    read(root, "packages/cli/templates/manifest.json")
  );
  const features = Object.entries(catalogue).filter(
    ([name, f]) => !f.deprecated && name !== "app-scaffold"
  );

  const sections = COMMANDS.map(([name, file]) => {
    const doc = leadingDocComment(read(root, file))
      .replace(/^`intelligo [^`]*`( —)?\s*/, "")
      .trim();
    let s = `## ${name}\n\n${doc.charAt(0).toUpperCase()}${doc.slice(1)}\n\n[source](${GITHUB}/blob/main/${file})`;
    if (name === "add") {
      s +=
        `\n\n| Feature | What it generates |\n| --- | --- |\n` +
        features
          .map(
            ([f, def]) =>
              `| \`${f}\` | ${def.description.replace(/\|/g, "\\|")} — ${def.files.map((x) => `\`${x.target}\``).join(", ")} |`
          )
          .join("\n");
    }
    return s;
  });

  const pkg = JSON.parse(read(root, "packages/cli/package.json"));
  return {
    "cli/index.md":
      frontmatter({
        title: "CLI",
        description: `${pkg.description} Every section below is the command's own source documentation.`,
        order: 0,
        label: "Commands",
      }) +
      `${marker("packages/cli/src (usage and command doc comments) and packages/cli/templates/manifest.json")}\n\n` +
      "A scaffolded app has `@intelligo-dev/cli` as a dev dependency; run it with `pnpm exec intelligo`.\n\n" +
      "```text\n" +
      usage +
      "\n```\n\n" +
      sections.join("\n\n") +
      "\n",
  };
}

function stripMarkdown(s) {
  return s
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[`*_]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function firstSentences(s, max) {
  if (s.length <= max) return s;
  const cut = s.slice(0, max);
  const end = cut.lastIndexOf(". ");
  return end > 60 ? cut.slice(0, end + 1) : `${cut.replace(/\s+\S*$/, "")}…`;
}

// --- registry: install order and seams -----------------------------------

function installOrder(requires) {
  const items = requires.items;
  const order = [];
  const seen = new Set();
  const visit = (n) => {
    if (seen.has(n)) return;
    seen.add(n);
    for (const d of items[n]?.items ?? []) visit(d);
    order.push(n);
  };
  Object.keys(items)
    .filter((n) => n !== "smoke")
    .forEach(visit);
  return order;
}

function registryPages(root) {
  const requires = JSON.parse(read(root, "packages/registry/requires.json"));
  const registry = JSON.parse(read(root, "packages/registry/registry.json"));
  const blocks = registry.items.filter(
    (i) => i.type === "registry:block" && i.name !== "smoke"
  );
  const order = installOrder(requires);

  const rows = order.map((n) => {
    const r = requires.items[n] ?? {};
    const cell = (xs, fmt) => (xs?.length ? xs.map(fmt).join(", ") : "—");
    return `| [${n}](/blocks/${n}) | ${cell(r.items, (x) => `[${x}](/blocks/${x})`)} | ${cell(r.files, (x) => `\`${x}\``)} | ${cell(r.features, (x) => `\`${x}\``)} |`;
  });

  const out = {};
  out["registry/install-order.md"] =
    frontmatter({
      title: "Install order",
      description:
        "Which blocks need another block first, which scaffold files each imports and which feature keys each gates on — the order CI installs in.",
      order: 1,
    }) +
    `${marker("packages/registry/requires.json")}\n\n` +
    "Run these inside the app, top to bottom, and every block finds what it imports. The first line is the design-system base — tokens, fonts and the base-nova config every block is drawn with — which `intelligo create` installs for you. `@intelligo` is the registry the scaffold's `components.json` names. `intelligo doctor` checks an installed app against the same requirements.\n\n" +
    "```bash\n" +
    ["intelligo", ...order]
      .map((n) => `pnpm exec shadcn add @intelligo/${n}`)
      .join("\n") +
    "\n```\n\n" +
    "| Block | Needs these blocks | Imports these scaffold files | Gates on these features |\n| --- | --- | --- | --- |\n" +
    rows.join("\n") +
    "\n\n" +
    "A feature key must be granted to a plan in `lib/plans.ts`; an unregistered feature is denied on every request.\n\n" +
    `Scaffold files a block may import, all written by \`intelligo create\`: ${requires.scaffold.map((s) => `\`${s}\``).join(", ")}.\n`;

  const seams = seamMap(root, registry);
  const sections = blocks
    .filter((b) => seams[b.name]?.length)
    .map((b) => {
      const parts = seams[b.name].map((target) => {
        const file = (b.files ?? []).find((f) => f.target === target);
        const source = `packages/registry/${file.path}`;
        const text = read(root, source);
        const exports = [
          ...text.matchAll(
            /^export (?:async )?(?:function|const|interface|type|class) (\w+)/gm
          ),
        ].map((m) => `\`${m[1]}\``);
        const doc = leadingDocComment(text);
        return `### \`${target}\`\n\n${exports.length ? `Exports ${exports.join(", ")}. ` : ""}[source](${GITHUB}/blob/main/${source})\n\n${doc}`;
      });
      return `## [${b.name}](/blocks/${b.name})\n\n${parts.join("\n\n")}`;
    });

  out["registry/config-seams.md"] =
    frontmatter({
      title: "Config seams",
      description:
        "Every file a block ships for you to edit — navigation, banners, onboarding, credit bundles, the chat's identity, tools and canvas — with the documentation each file carries.",
      order: 2,
    }) +
    `${marker("packages/registry/registry.json and each seam file's doc comment")}\n\n` +
    "Installed components are used verbatim. What a deployment varies lives in these files: they are consumer-owned, and each explains itself in the comment it ships with, reproduced here. If a product needs something no seam offers, the change belongs in the registry as a new seam — editing an installed component forks you from every later improvement to it.\n\n" +
    sections.join("\n\n") +
    "\n";
  return out;
}

// --- environment ------------------------------------------------------------

const ENV_TEMPLATE = "packages/cli/templates/app-scaffold/env.example.tpl";

/** Read by the packages but not a deployment's to set, or covered by another variable's entry. */
const ENV_NOT_DOCUMENTED = new Set([
  "NODE_ENV",
  "TEST_PG_URL",
  // The legacy alias BETTER_AUTH_SECRET's entry names.
  "AUTH_SECRET",
]);

/** `.env.example` → sections of { names, value, text }, one entry per commented group. */
function parseEnvTemplate(text) {
  const sections = [];
  let entry = null;
  let comment = [];
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^# =+$/.test(line)) {
      if (/^# =+$/.test(lines[i + 2] ?? "")) {
        sections.push({
          title: lines[i + 1].replace(/^# /, "").replace(/\.$/, ""),
          entries: [],
        });
        i += 2;
      }
      continue;
    }
    const variable = line.match(/^(?:# )?([A-Z][A-Z0-9_]*)=(.*)$/);
    if (variable) {
      if (comment.length || !entry) {
        entry = { names: [], value: "", text: comment.join(" ") };
        sections.at(-1).entries.push(entry);
        comment = [];
      }
      entry.names.push(variable[1]);
      entry.value ||= variable[2];
      continue;
    }
    if (line.startsWith("# ")) comment.push(line.slice(2).trim());
    else if (line.trim() === "") entry = null;
  }
  return sections;
}

function environmentPage(root) {
  const sections = parseEnvTemplate(read(root, ENV_TEMPLATE));
  const documented = new Set(
    sections.flatMap((s) => s.entries.flatMap((e) => e.names))
  );

  const undocumented = new Set();
  for (const { dir } of publishedPackages(root)) {
    const src = join(root, "packages", dir, "src");
    if (!existsSync(src)) continue;
    for (const file of walkFiles(src)) {
      if (!/\.tsx?$/.test(file) || /\.test\.tsx?$/.test(file)) continue;
      for (const m of readFileSync(file, "utf8").matchAll(
        /process\.env\.([A-Z][A-Z0-9_]*)/g
      )) {
        if (!documented.has(m[1]) && !ENV_NOT_DOCUMENTED.has(m[1]))
          undocumented.add(m[1]);
      }
    }
  }
  if (undocumented.size)
    throw new Error(
      `docs: the packages read ${[...undocumented].join(", ")}, which ${ENV_TEMPLATE} does not document — add them there`
    );

  const cell = (t) => t.replace(/\|/g, "\\|").replace(/</g, "&lt;");
  const body = sections
    .map((s) => {
      const rows = s.entries.map((e) => {
        const names = e.names.map((n) => `\`${n}\``).join("<br>");
        const value = e.value.replace("__APP_SLUG__", "your-app");
        const example = value ? ` The scaffold sets \`${value}\`.` : "";
        return `| ${names} | ${cell(e.text)}${example} |`;
      });
      return `## ${s.title}\n\n| Variable | What it is |\n| --- | --- |\n${rows.join("\n")}`;
    })
    .join("\n\n");

  return {
    "getting-started/environment.md":
      frontmatter({
        title: "Environment variables",
        description:
          "Every variable an Intelligo app reads — the two it cannot boot without, and the ones that switch on email, OAuth, Stripe, the maintenance cron and the admin console.",
        label: "Environment",
        order: 2,
      }) +
      `${marker(`${ENV_TEMPLATE} — the \`.env.example\` every new app gets`)}\n\n` +
      "`intelligo create` writes these to `.env.example`; copy it to `.env.local` and fill it in. `intelligo doctor` reports what is still missing, and the app refuses to boot without the required ones rather than failing when a feature is first used. `AUTH_SECRET` is accepted as a legacy alias of `BETTER_AUTH_SECRET`.\n\n" +
      body +
      "\n",
  };
}

/** Block name → the seam files it installs. Also written to src/data/seams.json for the site. */
export function seamMap(
  root,
  registry = JSON.parse(read(root, "packages/registry/registry.json"))
) {
  return Object.fromEntries(
    registry.items
      .filter((i) => i.type === "registry:block" && i.name !== "smoke")
      .map((i) => [
        i.name,
        (i.files ?? [])
          .filter((f) => {
            const target = f.target ?? f.path;
            if (SEAM.test(target)) return true;
            if (!/^lib\/.*\.tsx?$/.test(target)) return false;
            const doc = leadingDocComment(
              read(root, `packages/registry/${f.path}`)
            );
            return SAYS_CONSUMER_OWNED.test(doc);
          })
          .map((f) => f.target ?? f.path),
      ])
  );
}

/** Every generated docs page, keyed by path under DOCS_DIR. */
export function generateDocs(root) {
  const pages = {
    ...packagePages(root),
    ...cliPage(root),
    ...registryPages(root),
    ...environmentPage(root),
  };
  return Object.fromEntries(
    Object.entries(pages).map(([rel, md]) => [rel, stripAdrRefs(md)])
  );
}

/** Data files the site reads, keyed by path under the site. */
export function generateData(root) {
  return {
    "src/data/requires.json": read(root, "packages/registry/requires.json"),
    "src/data/seams.json": JSON.stringify(seamMap(root), null, 2) + "\n",
  };
}

// --- snippets ---------------------------------------------------------------

const SNIPPET =
  /(<!-- snippet: ([^\s#]+)(?:#(\w+))? -->\n+)([ \t]*)(`{3,})([^\n]*)\n(?:[\s\S]*?\n)??\4\5\n/g;

/** Replace every snippet-marked fence with the current source; returns the new text. */
export function applySnippets(markdown, root) {
  return markdown.replace(
    SNIPPET,
    (_, head, path, symbol, indent, fence, info) => {
      const code = extract(root, path, symbol)
        .split("\n")
        .map((l) => (l ? indent + l : l))
        .join("\n");
      return `${head}${indent}${fence}${info}\n${code}\n${indent}${fence}\n`;
    }
  );
}

/** The snippets a Markdown file declares, for tests. */
export function snippetRefs(markdown) {
  return [...markdown.matchAll(SNIPPET)].map((m) => ({
    path: m[2],
    symbol: m[3],
  }));
}

let ts;
function typescript(root) {
  ts ??= createRequire(resolve(root, "package.json"))("typescript");
  return ts;
}

function extract(root, path, symbol) {
  const file = join(root, path);
  if (!existsSync(file)) throw new Error(`snippet: ${path} does not exist`);
  let text = readFileSync(file, "utf8");
  if (path.endsWith(".tpl"))
    text = text.replace(/__APP_(NAME|SLUG)__/g, "my-app");
  if (!symbol) {
    // The whole file, without the doc comment it opens with.
    return text
      .replace(/^(\s*("use (client|server)";|import "server-only";)\s*)*/, "")
      .replace(/^\s*\/\*\*[\s\S]*?\*\/\s*/, "")
      .trimEnd();
  }
  const T = typescript(root);
  const sf = T.createSourceFile(
    basename(path).replace(/\.tpl$/, ""),
    text,
    T.ScriptTarget.Latest,
    true,
    T.ScriptKind.TSX
  );
  for (const st of sf.statements) {
    const names = T.isVariableStatement(st)
      ? st.declarationList.declarations.map((d) => d.name.getText(sf))
      : st.name
        ? [st.name.getText(sf)]
        : [];
    if (names.includes(symbol))
      return text.slice(st.getStart(sf), st.end).trimEnd();
  }
  throw new Error(
    `snippet: ${path} has no top-level declaration named ${symbol}`
  );
}

/** Every Markdown file under the docs directory, as paths relative to it. */
export function docFiles(siteRoot) {
  const base = resolve(siteRoot, DOCS_DIR);
  const out = [];
  const walk = (d) => {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else if (name.endsWith(".md"))
        out.push(relative(base, p).split("\\").join("/"));
    }
  };
  if (existsSync(base)) walk(base);
  return out.sort();
}

// --- llms.txt ---------------------------------------------------------------

/** A folder's index.md is the section's own page, at the folder's id. */
function docId(rel) {
  return rel.replace(/\.md$/, "").replace(/\/?index$/, "");
}

const GENERATED_MARKER =
  /^<!-- Generated by apps\/site\/scripts\/docs\.mjs[^\n]*-->\n*/;

/** The `---\nkey: value\n---` block every doc frontmatter is, in practice: one scalar per line, some JSON-quoted (generated pages), some bare (hand-written ones). */
function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) return { fields: {}, body: text };
  const fields = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    const raw = kv[2].trim();
    fields[kv[1]] = /^".*"$/.test(raw) ? JSON.parse(raw) : raw;
  }
  return { fields, body: text.slice(m[0].length) };
}

/**
 * llms.txt (the llmstxt.org convention: a curated Markdown index for an
 * LLM/agent instead of rendered HTML) and a full-text mirror that
 * concatenates every doc, keyed by path under the site. Both are a
 * different render of the exact same committed docs generateDocs() and
 * every hand-written page already carry — nothing new to author.
 */
export function generateLlmsTxt(siteRoot) {
  const docsRoot = resolve(siteRoot, DOCS_DIR);
  const siteTs = read(siteRoot, "src/lib/site.ts");
  const description = siteTs.match(/description:\s*\n?\s*"([^"]+)"/)?.[1];
  if (!description)
    throw new Error(
      "llms.txt: could not find SITE.description in src/lib/site.ts"
    );

  const entries = docFiles(siteRoot)
    .map((rel) => {
      const { fields, body } = parseFrontmatter(
        readFileSync(join(docsRoot, rel), "utf8")
      );
      return {
        section: rel.split("/")[0],
        id: docId(rel),
        title: fields.title,
        description: fields.description,
        order: fields.order ?? 100,
        body: body.replace(GENERATED_MARKER, "").trim(),
      };
    })
    .sort((a, b) => {
      const rank = (e) => DOC_SECTIONS.findIndex((s) => s.id === e.section);
      return rank(a) - rank(b) || a.order - b.order || a.id.localeCompare(b.id);
    });

  const index =
    `# intelligo\n\n> ${description}\n\n` +
    DOC_SECTIONS.map(({ id, title }) => {
      const items = entries.filter((e) => e.section === id);
      if (!items.length) return "";
      return (
        `## ${title}\n\n` +
        items
          .map(
            (e) => `- [${e.title}](${SITE_URL}/docs/${e.id}): ${e.description}`
          )
          .join("\n") +
        "\n"
      );
    })
      .filter(Boolean)
      .join("\n") +
    "\n## More\n\n" +
    `- [Blocks](${SITE_URL}/blocks): every registry item, rendered live from its installed source.\n` +
    `- [Components](${SITE_URL}/components): the base-nova design system catalog.\n` +
    `- [Hosted registry](${SITE_URL}/r/intelligo.json): install any item with the shadcn CLI.\n` +
    `- [Source](${GITHUB})\n`;

  const full =
    entries
      .map(
        (e) => `# ${e.title}\n\nSource: ${SITE_URL}/docs/${e.id}\n\n${e.body}`
      )
      .join("\n\n---\n\n") + "\n";

  return {
    "public/llms.txt": index,
    "public/llms-full.txt": full,
  };
}
